version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalogredis:
    container_name: catalogredis
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "RedisSettings:ConnectionString=catalogredis:6379"
    depends_on:
      - catalogdb
      - catalogredis
    ports:
      - "5000:80"